# .project metadata for KServe
# Documentation: https://github.com/cncf/automation/tree/main/utilities/dot-project

# TODO: Add package_managers if distributed via registries

schema_version: "1.0.0"
slug: "kserve"
name: "KServe"
description: "Standardized Distributed Generative and Predictive AI Inference Platform for Scalable, Multi-Framework Deployment on Kubernetes"
type: "project"
project_lead: "yuzisun" # TODO: AUTO-DETECTED — please verify
slack_channels:
  - name: "#kserve"
    primary: true
  - name: "#kserve-contributors"
    primary: false

maturity_log:
  - phase: "incubating"
    date: "2025-09-29T00:00:00Z"
    issue: "https://github.com/cncf/toc/issues/1905"

repositories:
  - "https://github.com/kserve/kserve"

website: "https://kserve.github.io/website/"

artwork: "https://landscape.cncf.io/logos/./k-serve-color.svg"

adopters:
  path: "https://github.com/kserve/website/blob/main/docs/community/adopters.md"


# TODO: Add package manager identifiers if your project is distributed via registries
# package_managers:
#   docker: "kserve/kserve"


security:
  policy:
    path: "https://github.com/kserve/kserve/blob/master/SECURITY.md"
  contact:
    advisory_url: "https://github.com/kserve/kserve/security/advisories/new"

governance:
  contributing:
    path: "https://github.com/kserve/kserve/blob/master/CONTRIBUTING.md"
  code_of_conduct:
    path: "https://github.com/kserve/kserve/blob/master/CODE_OF_CONDUCT.md"

legal:
  license:
    path: "https://github.com/kserve/kserve/blob/master/LICENSE"
  identity_type:
    has_dco: true
    has_cla: false
    dco_url:
      path: "https://developercertificate.org/"

documentation:
  readme:
    path: "https://github.com/kserve/kserve/blob/master/README.md"

landscape:
  category: "Inference"
  subcategory: "Framework"

# CLOMonitor Score: 76/100
# Documentation: 84 | License: 86 | Best Practices: 62 | Security: 72
